### ISSUE TITLE
Voice chat indicator

### ISSUE THREAD

**Issue by VLBRTN** [Saltssaumure/pios-discord-theme#12]
In voice chat, when i say something, the voice chat indicator circle appears. That looks wierd in RadialStatus for piOS.
P. S. I have avatar with alpha channel.
![image](https://user-images.githubusercontent.com/67109628/162563228-689d1c19-3126-4bb0-bf04-28036392c326.png)

**Comment by Saltssaumure** [comment]
Thanks for the bug report! I'll see if there's a quick fix that I can apply on this end. You might also want to bring it up over on [RadialStatus](https://github.com/DiscordStyles/RadialStatus) too, since then they could fix it for everyone using any implementation of RadialStatus.
