### ISSUE TITLE
Replying in minimal mode overlap timestamps/username

### ISSUE THREAD

**Issue by BaHuu** [Saltssaumure/pios-discord-theme#13]
I use Discord in a rather slim mode (Because I use it on a vertical monitor) and i couldn't help but notice that if the message that they're reply is long this happens:
![image](https://user-images.githubusercontent.com/33262120/163671619-fc104790-0171-45d5-8c11-717303511cc9.png)
I hope you can fix it. Nonetheless, the theme still looks awesome.

**Comment by Saltssaumure** [comment]
I've been meaning to revamp the reply section for a while, there's other issues it causes too. Thanks for reporting so that I'm motivated to fix it!

**Comment by Saltssaumure** [comment]
![image](https://user-images.githubusercontent.com/29710355/163703564-a4a810e7-9166-44bd-9d38-3d34cff8a5fe.png)
Fixed now :)
