### ISSUE TITLE
Profile button bug

### ISSUE THREAD

**Issue by VLBRTN** [Saltssaumure/pios-discord-theme#14]
When hovering over the user's avatar, the profile button moves down a little.
![image](https://user-images.githubusercontent.com/67109628/163703154-0c1c3462-950c-4537-a2d6-17ef821733e4.png)

**Comment by Saltssaumure** [comment]
Thanks for the report, should be fixed now 
![image](https://user-images.githubusercontent.com/29710355/163706343-6d55b9bb-283c-4c10-b696-9d86429a7430.png)
