### ISSUE TITLE
Misaligned thread element

### ISSUE THREAD

**Issue by RadsammyT** [Saltssaumure/pios-discord-theme#15]
although the spine of the thread is aligned (referring to issue #9 ) the extendable base of it isn't, often misaligning towards the message itself 

![wVDsNongWg](https://user-images.githubusercontent.com/32146976/164984564-167e7021-b912-45fb-bd97-4463b97bfa70.png)

**Comment by Saltssaumure** [comment]
Thanks for the report! Should be fixed now:
![image](https://user-images.githubusercontent.com/29710355/164996052-7eeee179-6e99-4b73-a22e-6c32047e1349.png)
