### ISSUE TITLE
Bots "used" message looks wierd.

### ISSUE THREAD

**Issue by VLBRTN** [Saltssaumure/pios-discord-theme#17]
As example - MEE6 and its command /set-user-birthday.
![image](https://user-images.githubusercontent.com/67109628/168446451-6facc2ab-dc19-4a88-a42f-262afd2f6eb9.png)

**Comment by Saltssaumure** [comment]
Thanks for letting me know, should be fixed now: 
![image](https://user-images.githubusercontent.com/29710355/168495371-3a54a9f7-f8c9-4955-b7d2-1edc1bfd16f1.png)
