### ISSUE TITLE
Problem with Cyrillic and theme font

### ISSUE THREAD

**Issue by Roma1825** [Saltssaumure/pios-discord-theme#25]
I like the original theme font, but I mostly communicate in Cyrillic and the theme does not support it. But I see in the files a font named FixedSys Excelsior, which is perfect for my case. So, any solution, how do I change it to this font if it's already there? Or is this option easier to solve by downloading the whole theme and editing it manually? anyway.

**Comment by Saltssaumure** [comment]
Should be fixed as of 425bb19bb05ea619c07fc84d55e62fc792b22c94 👍
