### ISSUE TITLE
Scanlines in images

### ISSUE THREAD

**Issue by flibety** [Saltssaumure/pios-discord-theme#31]
could there be a way to disable scanlines over images that have been sent? or to at least remove them when you click on an image to enlarge it

**Comment by Saltssaumure** [comment]
Add this to your Custom/Quick CSS to move the scanline layer beneath the enlarged images:
```css
:root {
    --crt-height: 1001;
}
```
Note that this will also remove scanlines from other popups, eg. user profiles.
