### ISSUE TITLE
Missing "connected from phone" icon

### ISSUE THREAD

**Issue by ElTioRata** [Saltssaumure/pios-discord-theme#33]
I can't distinguish users connected from different devices with this theme enabled.

**Comment by Saltssaumure** [comment]
In custom/quick CSS, add this to restore a phone symbol inside the profile picture.
```css
:root {
    --rs-phone-visible: block;
}
```
However it would be preferable to use the PlatformIndicators plugin to add a large icon beside the username.

(both options are shown in the picture below)
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/29710355/a7ab28c1-3e9e-4c31-8bb1-3cb670306059)
