### ISSUE TITLE
Hovering over rounded server picture in side panel it become square

### ISSUE THREAD

**Issue by Xrdem** [Saltssaumure/pios-discord-theme#34]
When client start all server pictures seen rounded. like this.. 

![Capture](https://github.com/Saltssaumure/pios-discord-theme/assets/116120205/0e15180b-ebd8-4d27-b5f4-d7d865aa606f)

When you hover it it becomes square shaped pictures.
like this...

![Capture2](https://github.com/Saltssaumure/pios-discord-theme/assets/116120205/1b8664a3-4555-404b-a20e-daedfc3820ac)

**Comment by Saltssaumure** [comment]
An issue with MiniDiscordThemes/Squared, now fixed
