### ISSUE TITLE
icons misalign, might be based on profile image size?

### ISSUE THREAD

**Issue by soupcantrolling** [Saltssaumure/pios-discord-theme#38]
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/104684447/b4659c68-62fa-4949-b0dd-74c406fe4106)
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/104684447/6bd14f02-4bd6-4d80-b95f-d7dec24079da)

**Comment by Saltssaumure** [comment]
Where are these pfps located? eg. in server members list?

**Comment by Saltssaumure** [comment]
Closing for now due to lack of followup, please reopen if you still have this issue.
