### ISSUE TITLE
how can delete the effect of old tv

### ISSUE THREAD

**Issue by elkapokogu** [Saltssaumure/pios-discord-theme#41]
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/169864667/fd0aece5-f9ea-476b-a078-0cf5226fb899)

**Comment by Saltssaumure** [comment]
Set `--crt-stripe` to `none`. See the [full customisation instructions](https://github.com/Saltssaumure/pios-discord-theme#customisation) on how to do this for your client mod.
