### ISSUE TITLE
Vencord fails to load updated theme

### ISSUE THREAD

**Issue by AeliusSaionji** [Saltssaumure/pios-discord-theme#42]
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/4342746/71705b4c-09f9-4450-884d-02768c919f34)

`Error: s.headers.get is not a function`

I have not tried prior versions of this theme.

**Comment by Saltssaumure** [comment]
Temporary issue caused by ISP blocking, should now be resolved.
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/29710355/7ebb59ae-4ebc-4b56-a647-203ccf683a7a)
![image](https://github.com/Saltssaumure/pios-discord-theme/assets/29710355/0b7b31dc-31fa-4639-8462-dfb192bf5a0c)
