### ISSUE TITLE
Threads problem in piOS

### ISSUE THREAD

**Issue by VLBRTN** [Saltssaumure/pios-discord-theme#9]
So...
Here's what happends, when someone creates a thread from a message.
![image](https://user-images.githubusercontent.com/67109628/160184876-9bf087a7-a58c-49bf-a97e-e062d9cf5770.png)

**Comment by Saltssaumure** [comment]
Thanks for letting me know, should be fixed now 👍
![image](https://user-images.githubusercontent.com/29710355/162554124-f29b02df-b657-431e-93ab-9667a6c67c46.png)
